sudo: false
language: php
php:
  - 5.4
  - 5.5
  - 5.6
matrix:
  allow_failures:
    - php: hhvm
    - php: php-fpm
  fast_finish: true
env:
  global:
    - MAGENTO_DB_ALLOWSAME=1
    - SKIP_CLEANUP=1
    - TEST_BASEDIR=.modman/ApiPlus/dev/tests/apiplus
  matrix:
    - MAGENTO_VERSION=magento-mirror-1.9.2.1
script:
  - curl -sSL https://raw.githubusercontent.com/AOEpeople/MageTestStand/master/setup.sh | bash
notifications:
  email:
    recipients:
      - tiago@tiagosampaio.com
    on_success: always
    on_failure: always
